var __Indicator = [

  {
    id             : 'firn',
    field          : 'firn',
    enName         : 'Irrigated land area (net)',
    ruName         : 'Поливная площадь (нетто)',
    enUnit         : 'ha',
    ruUnit         : 'га',
    crops          : false,
    aggregation    : 'all',
    years          : false,
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'labeled',
    enLegend       : ['Irrigation area'],
    ruLegend       : ['Irrigation area'],    
    median         : 1575,
    maximum        : 2500,
    chart          : false,
    color          : '#e6550d'
 /* }, {
    id             : 'firb',
    field          : 'area_ha',
    enName         : 'Irrigated land area(gross)',
    ruName         : 'Площадь орошаемых земель (брутто)',
    enUnit         : 'ha',
    ruUnit         : 'га',
    crops          : false,
    aggregation    : 'all',
    years          : false,
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'labeled',
    chart          : 'KirFir',
    color          : '#de2d26'
  }, {
    id             : 'kir',
    field          : 'idx_kir',
    enName         : 'Land use coefficient',
    ruName         : 'Коэффициент землепользования',
    enUnit         : '',
    ruUnit         : '',
    crops          : false,
    aggregation    : 'all',
    years          : false,
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'coloured',
    median         : 0.63,
    maximum        : 1,
    chart          : 'KirFir',
    color          : ['#000', '#82b525']*/
  }, {
    id             : 'firf',
    field          : 'firf_{crop}',
    enName         : 'Irrigated crop acreage',
    ruName         : 'Орошаемые посевные площади с/х культур',
    enUnit         : 'ha',
    ruUnit         : 'га',
    crops          : ['sum', 'cotton', 'wheat', 'rice', 'other', 'orchard', 'garden', 'maize', 'veg', 'sun'],
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'labeled',
    enLegend       : ['Sum of crops', 'Cotton', 'Wheat', 'Rice', 'Other Crop', 'Orchard/Vineyard', 'Urban Garden', 'Maize', 'Vegetable', 'Sunflower'],
    ruLegend       : ['Sum of crops', 'хлопок', 'пшеница', 'рис', 'Other Crop', 'фруктовый сад/Виноградник', 'Urban Garden', 'Maize', 'Vegetable', 'Sunflower'],    
    median         : [1050, 300, 325, 125, 263, 125, 50, 38, 60, 15],
    maximum        : [5500, 2850, 2925, 2410, 2275, 2800, 300, 646, 715, 218],
    chart          : 'Defaults'
 /* }, {
    id             : 'firf_state',
    field          : 'idx_sta',
    enName         : 'State order acreage',
    ruName         : 'Гоc.заказ посевных площадей',
    enUnit         : 'ha',
    ruUnit         : 'га',
    crops          : false,
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'labeled',
    median         : 650,
    maximum        : 2950,
    chart          : 'Defaults',
    color          : '#6a3d9a'*/
  /*}, {
    id             : 'uirn',
    field          : 'uirn',
    enName         : 'Irrigated land use (net)',
    ruName         : 'Орошаемое землепользование (нетто)',
    enUnit         : '',
    ruUnit         : '',
    crops          : false,
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'coloured',
    median         : 81.2,
    maximum        : 220,
    chart          : 'Defaults',
    color          : '#de2d26',
    legendcolors   : ['#fee0d2','#fc9272','#de2d26']*/
  /*}, {
    id             : 'uirb',
    field          : 'idx_uir_brt',
    enName         : 'Irrigated land use (gross)',
    ruName         : 'Орошаемое землепользование (брутто)',
    enUnit         : '',
    ruUnit         : '',
    crops          : false,
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'coloured',
    median         : 42.0,
    maximum        : 220,
    chart          : 'Defaults',
    color          : '#e6550d'*/
  }, {
    id             : 'uiri',
    field          : 'uiri_{crop}',
    enName         : 'Irrigated land use (per crop)',
    ruName         : 'Орошаемое использование земель по с/х культуре',
    enUnit         : '%',
    ruUnit         : '%',
    crops          : ['sum', 'cotton', 'wheat', 'rice', 'other', 'orchard', 'garden', 'maize', 'veg', 'sun'],
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'coloured',
    enLegend       : ['Irrigated land use', 'Cotton', 'Wheat', 'Rice', 'Other Crop', 'Orchard/Vineyard', 'Urban Garden', 'Maize', 'Vegetable', 'Sunflower'],
    ruLegend       : ['нетто б земля', 'хлопок', 'пшеница', 'рис', 'Other Crop', 'фруктовый сад/Виноградник', 'Urban Garden', 'Maize', 'Vegetable', 'Sunflower'],    
    median         : [81.2, 18.4, 27.3, 4.6, 18.0, 7.9, 2.0, 3.8, 5.5, 1.6],
    maximum        : [220, 100, 100, 100, 100, 100, 100, 100, 100, 100],
    chart          : 'Defaults',
    legendcolors   : [['#fee0d2','#fc9272','#de2d26'],['#F1F6F2','#76A882','#3B5441'],['#F1F6F2','#FF7F00','#3B5441'],['#F1F6F2','#1F78B4','#3B5441'],['#F1F6F2','#DD3497','#3B5441'],['#F1F6F2','#00858E','#3B5441'],['#F1F6F2','#E31A1C','#3B5441'],['#F1F6F2','#33a02c','#3B5441'],['#F1F6F2','#6a3d9a','#3B5441'],['#F1F6F2','#FFD500','#3B5441']]  
  /*}, {
    id             : 'uir_state',
    field          : 'idx_sta_irr',
    enName         : 'State order land use',
    ruName         : 'Гос.заказ использование земли',
    enUnit         : '',
    ruUnit         : '',
    crops          : false,
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'coloured',
    median         : 49.3,
    maximum        : 118,
    chart          : 'Defaults',
    color          : '#6a3d9a'*/
  }, {
    id             : 'pirf',
    field          : 'pirf_{crop}',
    enName         : 'Farm gross output actual',
    ruName         : 'Ферма валовой продукции фактическая',
    enUnit         : 'tons',
    ruUnit         : 'тонны',
    crops          : ['cotton', 'wheat'],
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'labeled',
    enLegend       : ['Cotton', 'Wheat'],
    ruLegend       : ['Хлопок', 'Пшеница'],    
    median         : [[129, 306, 560, 923, 1475, 2577, 11907], [173, 408, 783, 1373, 2271, 3758, 15555]],
    chart          : 'Defaults'
  }, {
    id             : 'yield',
    field          : 'yield_{crop}',
    enName         : 'Yield',
    ruName         : 'Урожайность',
    enUnit         : 't/ha',
    ruUnit         : 'т/га',
    crops          : ['cotton', 'wheat'],
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'coloured',
    enLegend       : ['Cotton', 'Wheat'],
    ruLegend       : ['Хлопок', 'Пшеница'],
    median         : [[1.46, 1.73, 2, 2.39, 2.94, 3.6, 25.5], [1.84, 2.27, 2.66, 3.09, 3.53, 4.06, 8.74]],
    chart          : 'Defaults',
    legendcolors   : ['#ffff80','#f8db5a','#f0b92f','#e69900','#a38f21','#56823b','#00734c']
  /*}, {
    id             : 'intensity',
    field          : 'double_percent',
    enName         : 'Land use intensity',
    ruName         : 'Интенсивность землепользования',
    enUnit         : '',
    ruUnit         : '',
    crops          : false,
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'analytical',
    mapType        : 'coloured',
    median         : 11.11,
    maximum        : 100,
    chart          : 'Defaults',
    color          : '#ccaa00'*/
  }, {
    id             : 'fallow',
    field          : 'fallow_percent',
    enName         : 'Temporarily unused irrigable land',
    ruName         : 'Неиспользованный орошаемые земли',
    enUnit         : '%',
    ruUnit         : '%',
    crops          : false,
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'analytical',
    mapType        : 'coloured',
    enLegend       : ['Fallow land'],
    ruLegend       : ['Площадь неисп. земель'],    
    median         : 37.50,
    maximum        : 100,
    chart          : 'Defaults',
    color          : '#b29972',
    legendcolors   : ['#F1F6F2','#B29972','#3B5441']
  }, {
    id             : 'majority',
    field          : 'majority',
    enName         : 'Major land use',
    ruName         : 'Основное землепользование',
    enUnit         : '',
    ruUnit         : '',
    crops          : false,
    aggregation    : ['grid'],
    years          : false,
    yearsPrefix    : true,
    category       : 'landuse',
    type           : 'analytical',
    mapType        : 'coloured',
    enLegend       : ['Predominant crop type'],
    ruLegend       : ['Преобладающий тип урожая'],
    enCropNames    : ['Cotton', 'Wheat', 'Rice', 'Fallow land', 'Double season', 'Other crops', 'Orchard/Vineyard', 'Urban Garden'],
    ruCropNames    : ['хлопок', 'пшеница', 'рис', 'Неиспользуемые земли', 'Double season', 'Другие культуры', 'фруктовый сад/Виноградник', 'Urban Garden'],
    chart          : 'Majority'
  }, {
    id             : 'diversity',
    field          : 'diversity',
    enName         : 'Crop rotation',
    ruName         : 'Разнообразие с/х культур',
    enUnit         : '',
    ruUnit         : '',
    crops          : false,
    aggregation    : ['grid'],
    years          : false,
    yearsPrefix    : true,
    category       : 'landuse',
    type           : 'analytical',
    mapType        : 'coloured',
    enLegend       : ['Number of crop types'],
    ruLegend       : ['Количество типов культур'],   
    median         : 3.4,
    maximum        : 6,
    chart          : 'Majority',
    color          : ['#000', '#f49d10']
  }, {
    id             : 'frequency',
    field          : 'frequency',
    enName         : 'Fallow land frequency',
    ruName         : 'Частота неисп.земель',
    enUnit         : '',
    ruUnit         : '',
    crops          : false,
    aggregation    : ['grid'],
    years          : false,
    yearsPrefix    : true,
    category       : 'landuse',
    type           : 'analytical',
    mapType        : 'coloured',
    enLegend       : ['Years of fallow'],
    ruLegend       : ['Years of fallow'],    
    median         : 6.7,
    maximum        : 16,
    chart          : 'Majority',
    color          : ['#000', '#82b525']
  }

];
