var __Indicator = [

  {
    id             : 'fir_n',
    field          : 'fir_n',
    new_id:'fir_n',
    enName         : 'Net irrigated area',
    ruName         : 'Орошаемая площадь нетто',
    enNameShort         : 'Net irrigated area',
    ruNameShort         : 'Орошаемая площадь нетто',
enTooltip      : 'Area equipped with irrigation infrastructure',
ruTooltip      : 'Площадь оснащенная ирригационной инфраструктурой',
    enUnit         : 'ha',
    ruUnit         : 'га',
    crops          : false,
    aggregation    : 'all',
    years          : false,
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'labeled',
    enLegend       : ['Irrigated area'],
    ruLegend       : ['Поливная площадь'],
   // median         : 1464,
   // maximum        : 4710,
    median         : 0,
    maximum        : 0,
    chart          : false,
    decimals       : 0,
    glossary       : 'bme00073.htm'
    //color          : '#e6550d'
  }, {
    id             : 'firf',
    field          : 'firf_{crop}',
    new_id:'firf',
    enName         : 'Irrigated acreage per crop',
    ruName         : 'Посевная орошаемая площадь',
    enNameShort    : 'Irrigated acreage',
    ruNameShort    : 'Посевная орошаемая площадь',
enTooltip      : 'Area of active irrigated cropland',
ruTooltip      : 'Площадь активного орошаемых пахотных земель',
    enUnit         : 'ha',
    ruUnit         : 'га',
    crops          : ['sum', 'cotton', 'wheat', 'rice', 'other', 'orchard', 'garden', 'maize', 'veg', 'sun'],
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'labeled',
    enLegend       : ['All crops', 'Cotton', 'Wheat', 'Rice', 'Other Crop', 'Orchard/Vineyard', 'Urban Garden', 'Maize', 'Vegetable', 'Sunflower'],
    ruLegend       : ['Все зерновые культуры', 'хлопок', 'пшеница', 'рис', 'другая культура', 'фруктовый сад/Виноградник', 'Городской сад', 'кукуруза', 'овощной', 'подсолнух'],
    //median         : [1140, 306, 276, 54, 228, 60, 60, 59, 66, 11],
    //maximum        : [8286, 4230, 4152, 2650, 3756, 3288, 996, 1560, 1548, 469],
    median         : 0,
    maximum        : 0,
    chart          : ['Stacked', 'Defaults', 'Defaults', 'Defaults', 'Defaults', 'Defaults', 'Defaults', 'Defaults', 'Defaults', 'Defaults'],
    decimals       : 0,
    glossary       : 'bme00073.htm'
  }, {
    id             : 'uir',
    field          : 'uir_{crop}',
        new_id:'uir',
    enName         : 'Irrigated land use per crop',
    ruName         : 'Использование орошаемых земель под с/х культурами',
    enNameShort    : 'Irrigated land use',
    ruNameShort    : 'Использование орошаемых земель',
    enTooltip      : 'Use intensity in relation to net irrigated area',
    ruTooltip      : 'Используйте интенсивность по отношению к чистой орошаемой площади',
    enUnit         : '%',
    ruUnit         : '%',
    crops          : ['sum', 'cotton', 'wheat', 'rice', 'other', 'orchard', 'garden', 'maize', 'veg', 'sun'],
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'colored',
    enLegend       : ['All crops', 'Cotton', 'Wheat', 'Rice', 'Other Crop', 'Orchard/Vineyard', 'Urban Garden', 'Maize', 'Vegetable', 'Sunflower'],
    ruLegend       : ['Все зерновые культуры', 'хлопок', 'пшеница', 'рис', 'другая культура', 'фруктовый сад/Виноградник', 'Городской сад', 'кукуруза', 'овощной', 'подсолнух'],
   // median         : [90, 17, 26, 4, 16, 3, 3, 4, 5, 1],
   // maximum        : [200, 100, 100, 100, 100, 100, 100, 100, 100, 100],
    median         : 0,
    maximum        : 0,
    chart          : ['Stacked', 'Defaults', 'Defaults', 'Defaults', 'Defaults', 'Defaults', 'Defaults', 'Defaults', 'Defaults', 'Defaults'],
    legendcolors   : [['#fee0d2','#fc9272','#de2d26'],['#F1F6F2','#76A882','#3B5441'],['#F1F6F2','#FF7F00','#3B5441'],['#F1F6F2','#1F78B4','#3B5441'],['#F1F6F2','#DD3497','#3B5441'],['#F1F6F2','#00858E','#3B5441'],['#F1F6F2','#E31A1C','#3B5441'],['#F1F6F2','#33a02c','#3B5441'],['#F1F6F2','#6a3d9a','#3B5441'],['#F1F6F2','#FFD500','#3B5441']] ,
    decimals       : 1,
    glossary       : 'bme00073.htm'
  }, {
    id             : 'pirf',
    field          : 'pirf_{crop}',
        new_id:'pirf',
    enName         : 'Farm gross output actual',
    ruName         : 'Фактическая валовая продукция',
    enNameShort         : 'Gross output',
    ruNameShort         : 'Валовая продукция ',
enTooltip      : 'Harvest quantity of irrigated land',
ruTooltip      : 'Урожай количество орошаемых земель',
    enUnit         : 'tons',
    ruUnit         : 'тонны',
    crops          : ['cotton', 'wheat'],
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'labeled',
    enLegend       : ['Cotton', 'Wheat'],
    ruLegend       : ['Хлопок', 'Пшеница'],
    // median         : [[87,270,591,1135,2044,3624,13182], [106,353,761,1421,2511,4371,16691]],
    median         : 0,
    maximum        : 0,
    chart          : 'Defaults',
    decimals       : 0,
    glossary       : 'bme00073.htm'
  }, {
    id             : 'y',
    field          : 'y_{crop}',
        new_id:'y',
    enName         : 'Yield',
    ruName         : 'Урожайность',
    enNameShort         : 'Yield',
    ruNameShort         : 'Урожайность',
enTooltip      : 'Crop productivity of irrigated land',
ruTooltip      : 'Урожайность орошаемых земель',
    enUnit         : 't/ha',
    ruUnit         : 'т/га',
    crops          : ['cotton', 'wheat'],
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'descriptive',
    mapType        : 'colored',
    enLegend       : ['Cotton', 'Wheat'],
    ruLegend       : ['Хлопок', 'Пшеница'],
    // median         : [[1.6, 1.9, 2.2, 2.54, 3.1, 3.7, 25.3], [1.9,2.3,2.7,3.1,3.6,4.1,8.2]],
    median         : 0,
    maximum        : 0,
    chart          : 'Defaults',
    legendcolors   : ['#ffff80','#f8db5a','#f0b92f','#e69900','#a38f21','#56823b','#00734c'],
    decimals       : 1,
    glossary       : 'bme00073.htm'
  }, {
    id             : 'fp',
    field          : 'fp',
        new_id:'fp',
    enName         : 'Temporary unused irrigable land',
    ruName         : 'Временно неиспользуемые орошаемые земли',
    enNameShort         : 'Fallow land',
    ruNameShort         : 'Временно неиспользуемые орошаемые земли',
enTooltip      : 'Non-use intensity in relation to net irrigated area',
ruTooltip      : 'Неиспользование интенсивность по отношению к чистой орошаемой площади',
    enUnit         : '%',
    ruUnit         : '%',
    crops          : false,
    aggregation    : 'all',
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'analytical',
    mapType        : 'colored',
    enLegend       : ['Fallow land'],
    ruLegend       : ['Площадь неисп. земель'],
    // median         : 28,
    // maximum        : 100,
    median         : 0,
    maximum        : 0,
    chart          : 'Defaults',
    color          : '#b29972',
    legendcolors   : ['#F1F6F2','#B29972','#3B5441'],
    decimals       : 1,
    glossary       : 'bme00073.htm'
}, {
    id             : 'cd',
    field          : 'cd',
        new_id:'cd',
    enName         : 'Crop diversity',
    ruName         : 'Разнообразие с/х культур',
    enNameShort         : 'Crop diversity',
    ruNameShort         : 'Разнообразие с/х культур',
enTooltip      : 'Index of diverse crop types of adjacent areas',
ruTooltip      : 'Индекс различных типов культур соседних областей',
    enUnit         : '-',
    ruUnit         : '-',
    crops          : false,
    aggregation    : ['grid'],
    years          : 'all',
    yearsPrefix    : false,
    category       : 'landuse',
    type           : 'analytical',
    mapType        : 'colored',
    enLegend       : ['Crop diversity index'],
    ruLegend       : ['Индекс разнообразия сельскохозяйственных культур'],
    // median         : 0.7,
    // maximum        : 1,
    median         : 0,
    maximum        : 0,
    chart          : 'Defaults',
    legendcolors   : ['#d7191c','#ffffbf', '#2c7bb6'],
    color          :'#989800',
    decimals       : 2,
    glossary       : 'bme00073.htm'
  }, {
    id             : 'mlu',
    field          : 'mlu',
        new_id:'mlu',
    enName         : 'Major land use',
    ruName         : 'Основные виды землепользования',
    enNameShort         : 'Major land use',
    ruNameShort         : 'Основные виды землепользования',
enTooltip      : 'Predominant crop type within the whole investigation period',
ruTooltip      : 'Преобладающий тип культур в течение всего периода исследования',
    enUnit         : '-',
    ruUnit         : '-',
    crops          : false,
    aggregation    : ['grid'],
    years          : false,
    yearsPrefix    : true,
    category       : 'landuse',
    type           : 'analytical',
    mapType        : 'colored',
    enLegend       : ['Predominant crop type'],
    ruLegend       : ['Преобладающий тип урожая'],
    croplist       : ['cotton', 'wheat', 'rice', 'fallow', 'double', 'other', 'orchard', 'garden'],
    enCropNames    : ['Cotton', 'Wheat', 'Rice', 'Fallow land', 'Wheat/Other crop', 'Other crop', 'Orchard/Vineyard', 'Urban Garden'],
    ruCropNames    : ['хлопок', 'пшеница', 'рис', 'Неиспользуемые земли', 'пшеница/другая культура', 'другая культура', 'фруктовый сад/Виноградник', 'Городской сад'],
    chart          : 'Multiannual',
    glossary       : 'bme00073.htm'
  }, {
    id             : 'cr',
    field          : 'cr',
        new_id:'cr',
    enName         : 'Crop rotation',
    ruName         : 'Севооборот',
    enNameShort         : 'Crop rotation',
    ruNameShort         : 'Севооборот',
enTooltip      : 'Average number of changing crop types within the whole investigation period',
ruTooltip      : 'Среднее количество изменения типов культур в течение всего периода исследования',
    enUnit         : '-',
    ruUnit         : '-',
    crops          : false,
    aggregation    : ['grid'],
    years          : false,
    yearsPrefix    : true,
    category       : 'landuse',
    type           : 'analytical',
    mapType        : 'colored',
    enLegend       : ['Number of crop types'],
    ruLegend       : ['Количество типов культур'],
    // median         : 3.4,
    // maximum        : 6,
    median         : 0,
    maximum        : 0,
    chart          : 'Multiannual',
    legendcolors   : ['#732A06','#e6550d', '#FCEEE6'],
    glossary       : 'bme00073.htm'
  }, {
    id             : 'flf',
    field          : 'flf',
        new_id:'flf',
    enName         : 'Fallow land frequency',
    ruName         : 'Частота неисп.земель',
     enNameShort         : 'Fallow land frequency',
    ruNameShort         : 'Частота неиспользования земель',
enTooltip      : 'Average number of unused years within the whole investigation period',
ruTooltip      : 'Среднее количество неиспользования земель в годах, в течение всего периода исследования',
    enUnit         : '-',
    ruUnit         : '-',
    crops          : false,
    aggregation    : ['grid'],
    years          : false,
    yearsPrefix    : true,
    category       : 'landuse',
    type           : 'analytical',
    mapType        : 'colored',
    enLegend       : ['Years of fallow'],
    ruLegend       : ['Годы залежные'],
    // median         : 6,
    // maximum        : 17,
    median         : 0,
    maximum        : 0,
    chart          : 'Multiannual',
    legendcolors   : ['#EAF5E9','#33a02c', '#195016'],
    glossary       : 'bme00073.htm'
  }

];
